---
title: "HM_figures"
author: "Abby Lewis"
date: "2026-01-20"
output: html_document
---

This file makes figure 2 (data) and figure 3 (totals/percents)

Load data and packages

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
library(tidyverse)
source("hm_style.R")
source("make_lm_label.R")

ch4 <- read_csv(here::here("01_Data", "GENX_flux_data_interpolated_with_drivers.csv")) %>%
  mutate(
    Chamber = factor(Chamber, levels = chamber_labels),
    date = as_date(DateTime_EST)
  )

soil_temp <- read_csv(here::here("01_Data", "Soil_temp.csv")) %>%
  mutate(Chamber = factor(Chamber, levels = chamber_labels))

n_days <- as.numeric(difftime(max(ch4$DateTime_EST),
  min(ch4$DateTime_EST),
  units = "days"
))
```

Summary stats

```{r}
ch4 %>%
  mutate(filled = ifelse(is.na(CH4_umol_m2_h_not_gapfilled) & !is.na(CH4_umol_m2_h), T, F)) %>%
  group_by(Chamber) %>%
  summarize(
    n = sum(filled),
    pct = n / sum(!is.na(CH4_umol_m2_h)) * 100
  ) %>%
  summarize(
    min(pct),
    max(pct)
  )
```

Data summary (Figure 2)

```{r}
min_annual <- min(ch4$date[!is.na(ch4$CH4_umol_m2_h)])
max_annual <- max(ch4$date[!is.na(ch4$CH4_umol_m2_h)])

annual <- ch4 %>%
  group_by(date, Chamber) %>%
  summarize(CH4_umol_m2_h = mean(CH4_umol_m2_h, na.rm = T)) %>%
  ggplot(aes(x = date, y = CH4_umol_m2_h, color = Chamber)) +
  geom_hline(yintercept = 0, color = "grey80") +
  geom_line(size = 0.5) +
  coord_cartesian(xlim = c(as_date(min_annual), as_date(max_annual))) +
  scale_color_manual(values = color.gradient, name = "Chamber") +
  theme_hm +
  theme(axis.title.x = element_blank()) +
  ylab(expression(atop(CH[4] ~ "flux", "(µmol" ~ m^-2 ~ h^-1 * ")")))

annual_ST <- soil_temp %>%
  mutate(date = as_date(DateTime_EST)) %>%
  group_by(date, Chamber) %>%
  summarize(Temp_C = mean(SoilTemp_C, na.rm = T)) %>%
  ggplot(aes(x = date, y = Temp_C, color = Chamber)) +
  geom_hline(yintercept = 0, color = "grey80") +
  geom_line(size = 0.5) +
  # coord_cartesian(xlim = c(as_date(min_annual), as_date(max_annual))) +
  scale_color_manual(values = color.gradient, name = "Chamber") +
  theme_hm +
  theme(axis.title.x = element_blank()) +
  ylab(expression(atop("Soil temp.", " (ºC)")))

annual_wl <- ch4 %>%
  group_by(date) %>%
  summarize(Depth_cm = mean(Depth_cm, na.rm = T)) %>%
  ggplot(aes(x = date, y = Depth_cm)) +
  geom_hline(yintercept = 0, color = "grey80") +
  geom_line(size = 0.5, color = "grey20") +
  coord_cartesian(xlim = c(as_date(min_annual), as_date(max_annual))) +
  theme_hm +
  theme(axis.title.x = element_blank()) +
  ylab(expression(atop("Water level", " (cm)")))

start_date <- "2025-03-27"
end_date <- "2025-04-06"

focal_ch4 <- ch4 %>%
  filter(date %in% seq.Date(as_date(start_date), as_date(end_date), by = "1 day")) %>%
  ggplot(aes(x = DateTime_EST, y = CH4_umol_m2_h, color = Chamber)) +
  geom_hline(yintercept = 0, color = "grey80") +
  geom_line(size = 0.5) +
  scale_color_manual(values = color.gradient, name = "Chamber") +
  theme_hm +
  theme(axis.title.x = element_blank()) +
  ylab(expression(atop(CH[4] ~ "flux ", "(µmol" ~ m^-2 ~ h^-1 * ")")))

focal_co2 <- ch4 %>%
  filter(date %in% seq.Date(as_date(start_date), as_date(end_date), by = "1 day")) %>%
  mutate(CO2_umol_m2_h = ifelse(hour(DateTime_EST) %in% 8:19, CO2_umol_m2_h, NA)) %>%
  ggplot(aes(x = DateTime_EST, y = CO2_umol_m2_h, color = Chamber)) +
  geom_hline(yintercept = 0, color = "grey80") +
  geom_line(size = 0.5) +
  scale_color_manual(values = color.gradient, name = "Chamber") +
  theme_hm +
  theme(axis.title.x = element_blank()) +
  ylab(expression(atop(CO[2] ~ "flux ", "(µmol" ~ m^-2 ~ h^-1 * ")")))

focal_wl <- ch4 %>%
  filter(date %in% seq.Date(as_date(start_date), as_date(end_date), by = "1 day")) %>%
  ggplot(aes(x = DateTime_EST, y = Depth_cm)) +
  geom_hline(yintercept = 0, color = "grey80") +
  geom_line(size = 0.5, color = "grey20") +
  theme_hm +
  theme(axis.title.x = element_blank()) +
  ylab(expression(atop("Water level", " (cm)")))

focal_ST <- soil_temp %>%
  mutate(date = as_date(DateTime_EST)) %>%
  filter(date %in% seq.Date(as_date(start_date), as_date(end_date), by = "1 day")) %>%
  ggplot(aes(x = DateTime_EST, y = SoilTemp_C, color = Chamber)) +
  geom_hline(yintercept = 0, color = "grey80") +
  geom_line(size = 0.5) +
  theme_hm +
  theme(axis.title.x = element_blank()) +
  scale_color_manual(values = color.gradient, name = "Chamber") +
  ylab(expression(atop("Soil temp.", " (ºC)")))

comb <- patchwork::wrap_plots(
  a = patchwork::wrap_plots(
    annual +
      guides(color = guide_legend(ncol = 4)) +
      theme(
        axis.text.x = element_blank(),
        axis.ticks.x = element_blank(),
        legend.position = "bottom"
      ) +
      ggtitle("Daily mean"),
    annual_ST +
      theme(
        axis.text.x = element_blank(),
        axis.ticks.x = element_blank(),
        legend.position = "none"
      ),
    annual_wl,
    ncol = 1, design = c("A
                          A
                          B
                          C")
  ),
  b = patchwork::wrap_plots(
    focal_ch4 +
      scale_x_datetime(date_breaks = "5 day", date_labels = "%d %b") +
      theme(
        axis.text.x = element_blank(),
        axis.ticks.x = element_blank(),
        axis.title.y = element_blank(),
        legend.position = "bottom"
      ) +
      ggtitle("Measured"),
    focal_ST +
      scale_x_datetime(date_breaks = "5 day", date_labels = "%d %b") +
      theme(
        axis.text.x = element_blank(),
        axis.ticks.x = element_blank(),
        legend.position = "none",
        axis.title.y = element_blank()
      ),
    focal_wl +
      scale_x_datetime(date_breaks = "5 day", date_labels = "%d %b") +
      theme(
        axis.title.y = element_blank(),
        legend.position = "none"
      ),
    ncol = 1,
    design = c("A
               A
               B
               C")
  ),
  ncol = 2, widths = c(2, 1),
  guides = "collect"
) +
  patchwork::plot_layout(guides = "collect") +
  patchwork::plot_annotation(
    tag_levels = list(c("a", "", "", "b")),
    theme = theme(
      legend.position = "bottom",
      legend.justification = "left",
      legend.title.position = "top"
    )
  ) &
  theme(plot.tag = element_text(face = "bold"))

comb

ggsave("../03_Figures/Figure 2 - Data drivers.jpg", dpi = 300, width = 7, height = 5)

patchwork::wrap_plots(
  annual +
    guides(color = guide_legend(ncol = 4)) +
    theme(
      axis.text.x = element_blank(),
      axis.ticks.x = element_blank(),
      legend.position = "bottom"
    ) +
    ggtitle("Daily mean"),
  annual_ST +
    theme(
      legend.position = "none"
    ),
  ncol = 1, design = c("A
                          A
                          B")
) +
  patchwork::plot_layout(guides = "collect") +
  patchwork::plot_annotation(
    tag_levels = list(c("a", "", "", "b")),
    theme = theme(
      legend.position = "bottom",
      legend.justification = "left",
      legend.title.position = "top"
    )
  ) &
  theme(plot.tag = element_text(face = "bold"))

ggsave("../03_Figures/Figure 2 - Data drivers pres.jpg", dpi = 300, width = 7, height = 5)
```

The importance of hot moment events increases with temperature (Figure 3)

```{r}
hm_df <- ch4 %>%
  filter(!is.na(CH4_umol_m2_h)) %>%
  group_by(date) %>%
  filter(length(unique(Chamber)) == 12)

hot_moments <- hm_df %>%
  group_by(Chamber) %>%
  mutate(
    hot_moment_quant_998 = ifelse(CH4_umol_m2_h >=
      quantile(CH4_umol_m2_h,
        probs = 0.998, na.rm = TRUE
      ),
    "hot", "not"
    ),
    hot_moment_quant_99 = ifelse(CH4_umol_m2_h >=
      quantile(CH4_umol_m2_h,
        probs = 0.99, na.rm = TRUE
      ),
    "hot", "not"
    ),
    hot_moment_quant_95 = ifelse(CH4_umol_m2_h >=
      quantile(CH4_umol_m2_h,
        probs = 0.95, na.rm = TRUE
      ),
    "hot", "not"
    )
  ) %>%
  summarize(
    n = sum(!is.na(CH4_umol_m2_h)),
    sum = sum(CH4_umol_m2_h, na.rm = T) /
      n / 1000 / 1000 * (n_days * 24), # Convert hourly fluxes to growing season
    hot_sum_998 = sum(CH4_umol_m2_h[hot_moment_quant_998 == "hot"], na.rm = T) /
      n / 1000 / 1000 * (n_days * 24),
    hot_sum_99 = sum(CH4_umol_m2_h[hot_moment_quant_99 == "hot"], na.rm = T) /
      n / 1000 / 1000 * (n_days * 24),
    hot_sum_95 = sum(CH4_umol_m2_h[hot_moment_quant_95 == "hot"], na.rm = T) /
      n / 1000 / 1000 * (n_days * 24),
    min = min(DateTime_EST),
    max = max(DateTime_EST)
  )

annual_df <- hot_moments %>%
  mutate(
    Temp_C = sub(" ºC", "", str_extract(as.character(Chamber), "[0-9]+\\.*[0-9]* ºC")),
    Temp_C = as.numeric(sub("mb", "0", Temp_C)),
    dif = as.numeric(difftime(max, min, "hours")),
    annual_flux = sum
  )

annual_label <- make_lm_label(
  data = annual_df,
  xvar = "Temp_C",
  yvar = "annual_flux"
)

annual <- annual_df %>%
  ggplot(aes(x = Temp_C, y = annual_flux)) +
  geom_smooth(method = "lm", color = "black") +
  geom_point(aes(fill = Chamber),
    color = "black", shape = 21,
    stroke = 0.5, size = 2
  ) +
  geom_text(
    aes(x = -Inf, y = Inf, label = annual_label$label),
    hjust = 0, vjust = 1.1,
    inherit.aes = FALSE,
    size = 3, data = data.frame()
  ) +
  scale_fill_manual(values = color.gradient, name = "Chamber") +
  theme_hm +
  ylab(expression(atop("Growing season", "emissions (mol" ~ m^-2 ~ yr^-1 * ")"))) +
  xlab("Temperature treatment (ºC above ambient)") +
  theme(
    legend.position = "bottom",
    legend.title.position = "top"
  ) +
  guides(fill = guide_legend(ncol = 2))

top_pct <- hot_moments %>%
  mutate(
    Temp_C = sub(" ºC", "", str_extract(as.character(Chamber), "[0-9]+\\.*[0-9]* ºC")),
    Temp_C = as.numeric(sub("mb", "0", Temp_C)),
    hm_pct_998 = hot_sum_998 / sum * 100,
    hm_pct_99 = hot_sum_99 / sum * 100,
    hm_pct_95 = hot_sum_95 / sum * 100
  ) %>%
  select(Temp_C, Chamber, hm_pct_998, hm_pct_99, hm_pct_95) %>%
  pivot_longer(c(hm_pct_95, hm_pct_99, hm_pct_998)) %>%
  mutate(
    name = factor(
      name,
      levels = c("hm_pct_95", "hm_pct_99", "hm_pct_998"),
      labels = c(
        "Top 5% of measurements",
        "Top 1% of measurements",
        "Top 0.2% of measurements"
      )
    )
  ) %>%
  group_by(name) %>%
  mutate(
    model  = list(lm(value ~ Temp_C)),
    p      = summary(model[[1]])$coefficients[2, 4],
    r2     = summary(model[[1]])$r.squared,
    median = median(value)
  ) %>%
  ungroup()

# Create label dataframe (one row per facet)
label_df <- top_pct %>%
  group_by(name) %>%
  summarise(
    p = first(p),
    r2 = first(r2),
    median = first(median),
    label = paste0(
      "  Median = ", round(median, 1), " %",
      "\n  R² = ", round(r2, 2),
      "\n  p = ", round(p, 3)
    )
  )

top_pct_fig <- top_pct %>%
  ggplot(aes(x = Temp_C, y = value)) +
  geom_smooth(
    method = "lm", color = "black",
    data = ~ subset(.x, p < 0.05)
  ) +
  geom_smooth(
    method = "lm", color = "grey70",
    data = ~ subset(.x, p >= 0.05),
    lty = "51", alpha = 0.15
  ) +
  geom_point(aes(fill = Chamber),
    color = "black", shape = 21,
    stroke = 0.5, size = 2
  ) +
  geom_text(
    data = label_df,
    aes(x = -Inf, y = Inf, label = label),
    hjust = 0, vjust = 1.1,
    inherit.aes = FALSE, size = 3
  ) +
  scale_fill_manual(values = color.gradient, name = "Chamber") +
  theme_hm +
  ylab(expression(atop("Percent of growing season", "emissions"))) +
  xlab("Temperature treatment (ºC above ambient)") +
  guides(fill = guide_legend(ncol = 4)) +
  facet_wrap(~name, scales = "free_y")

ggpubr::ggarrange(annual + theme(legend.position = "right"),
  top_pct_fig + theme(legend.position = "none"),
  nrow = 2, ncol = 1,
  labels = "auto"
)

ggsave(
  filename = "../03_Figures/Figure 3 - Top percent.jpg",
  dpi = 300, width = 6, height = 5
)

top_pct_pres <- top_pct %>%
  filter(name == "Top 1% of measurements") %>%
  ggplot(aes(x = Temp_C, y = value)) +
  geom_smooth(
    method = "lm", color = "black",
    data = ~ subset(.x, p < 0.05)
  ) +
  geom_point(aes(fill = Chamber),
    color = "black", shape = 21,
    stroke = 0.5, size = 2
  ) +
  geom_text(
    data = label_df %>%
      filter(name == "Top 1% of measurements"),
    aes(x = -Inf, y = Inf, label = label),
    hjust = 0, vjust = 1.1,
    inherit.aes = FALSE, size = 4
  ) +
  scale_fill_manual(values = color.gradient, name = "Chamber") +
  theme_hm +
  ylab(expression(atop("Top 1% of fluxes", "(% of growing season emissions)"))) +
  xlab("Temperature treatment (ºC above ambient)") +
  guides(fill = guide_legend(ncol = 3))

ggsave(
  top_pct_pres,
  filename = "../03_Figures/Figure 3 - Top percent pres.jpg",
  dpi = 300, width = 4, height = 5
)

comb <- patchwork::wrap_plots(
  annual + guides(fill = guide_legend(ncol = 3)),
  top_pct_pres,
  nrow = 1, ncol = 2,
  guides = "collect", axes = "collect_x"
) &
  theme(legend.position = "bottom")

ggsave(
  comb,
  filename = "../03_Figures/Figure 3 - Top percent pres comb.jpg",
  dpi = 300, width = 8, height = 4
)
```

Manual sampling underestimates

```{r}
reps <- 10000
set.seed(4700)

df <- ch4 %>%
  mutate(
    day = yday(date),
    month = month(date),
    week = week(date),
    fortnight = week %/% 2
  )

intervals <- c("daily", "twice weekly", "weekly", "fortnightly", "monthly")

calc_bias <- function(interval) {
  samples_per_bin <- case_when(grepl("twice", interval) ~ 2,
    .default = 1
  )
  bin_dur <- str_extract(interval, "daily|week|month|fortnight")
  bin_dur <- ifelse(bin_dur == "daily", "day", bin_dur)
  message(paste0("Running ", interval, ": \nBin: ", bin_dur, "\nSamples per bin: ", samples_per_bin))

  out_all <- df %>%
    group_by(get(bin_dur), Chamber) %>%
    reframe(
      n = n(),
      rep = seq_len(reps),
      flux = replicate(
        reps,
        mean(sample(CH4_umol_m2_h, samples_per_bin))
      ),
      interval = interval
    ) %>%
    mutate(time = "all")

  out_daytime <- df %>%
    filter(hour(DateTime_EST) %in% c(9:17)) %>%
    group_by(get(bin_dur), Chamber) %>%
    reframe(
      n = n(),
      rep = seq_len(reps),
      flux = replicate(
        reps,
        mean(sample(CH4_umol_m2_h, samples_per_bin))
      ),
      interval = interval
    ) %>%
    mutate(time = "daytime")

  out <- bind_rows(out_all, out_daytime)
  out
}

df_out <- purrr::map(intervals, calc_bias) %>%
  bind_rows()

to_plot <- df_out %>%
  group_by(Chamber, rep, interval, time) %>%
  summarize(
    mean_hourly = sum(flux * n / sum(n), na.rm = TRUE),
    tot_hourly = mean_hourly / 1e6 * (n_days * 24),
    .groups = "drop"
  ) %>%
  left_join(
    annual_df %>% rename(tot_real = annual_flux),
    by = "Chamber"
  ) %>%
  mutate(percent_bias = tot_hourly / tot_real * 100 - 100) %>%
  group_by(Chamber, interval, time) %>%
  summarize(
    median_bias = median(percent_bias, na.rm = TRUE),
    .groups = "drop"
  ) %>%
  mutate(
    Temp_C = sub(" ºC", "", str_extract(as.character(Chamber), "[0-9]+\\.*[0-9]* ºC")),
    Temp_C = as.numeric(sub("mb", "0", Temp_C))
  )

sims <- to_plot %>%
  mutate(
    interval = factor(interval, levels = intervals),
    int_num = as.numeric(interval)
  ) %>%
  ggplot(aes(color = Chamber, x = int_num, y = median_bias)) +
  geom_hline(yintercept = 0, color = "grey85") +
  geom_line(size = 0.5) +
  geom_point(aes(fill = Chamber), shape = 21, size = 2, stroke = 0.5) +
  scale_x_continuous(
    breaks = 1:length(intervals),
    labels = intervals
  ) +
  scale_fill_manual(
    values = color.gradient,
    name = "Chamber"
  ) +
  scale_color_manual(
    values = color.gradient,
    name = "Chamber"
  ) +
  theme_hm +
  theme(legend.title.position = "top") +
  ylab("Manual sampling bias (%)") +
  xlab("Simulated sampling interval") +
  guides(fill = guide_legend(ncol = 2)) +
  theme(axis.text.x = element_text(
    hjust = 1,
    angle = 45
  )) +
  facet_wrap(~time)

sims
ggsave(sims, filename = "../03_Figures/Figure 4 - Simulations multiple intervals.jpg", dpi = 300, width = 3, height = 4)

sims_full_day <- to_plot %>%
  filter(time == "all") %>%
  mutate(
    interval = factor(interval, levels = intervals),
    int_num = as.numeric(interval)
  ) %>%
  ggplot(aes(color = Chamber, x = int_num, y = median_bias)) +
  geom_hline(yintercept = 0, color = "grey85") +
  geom_line(size = 0.5) +
  geom_point(aes(fill = Chamber), shape = 21, size = 2, stroke = 0.5) +
  scale_x_continuous(
    breaks = 1:length(intervals),
    labels = intervals
  ) +
  scale_fill_manual(
    values = color.gradient,
    name = "Chamber"
  ) +
  scale_color_manual(
    values = color.gradient,
    name = "Chamber"
  ) +
  theme_hm +
  theme(legend.title.position = "top") +
  ylab("Manual sampling bias (%)") +
  xlab("Simulated sampling interval") +
  guides(fill = guide_legend(ncol = 2)) +
  theme(axis.text.x = element_text(
    hjust = 1,
    angle = 45
  ))

sims_full_day

sims_label <- make_lm_label(
  data = to_plot %>%
    filter(
      interval == "monthly",
      time == "all"
    ),
  xvar = "Temp_C",
  yvar = "median_bias"
)

sims_month <- to_plot %>%
  filter(
    interval == "monthly",
    time == "all"
  ) %>%
  ggplot(aes(x = as.numeric(Temp_C), y = median_bias, group = "group")) +
  geom_hline(yintercept = 0, color = "grey85") +
  geom_smooth(method = "lm", color = "black") +
  geom_point(aes(fill = Chamber), shape = 21, size = 2, stroke = 0.5) +
  geom_text(
    data = sims_label,
    aes(x = -Inf, y = -Inf, label = label),
    hjust = 0, vjust = -0.1,
    inherit.aes = FALSE, size = 3
  ) +
  scale_x_continuous(
    limits = c(-0.5, 6.5),
    expand = c(0, 0)
  ) +
  scale_fill_manual(
    values = color.gradient,
    name = "Chamber"
  ) +
  theme_hm +
  theme(legend.title.position = "top") +
  ylab("Manual sampling bias (%)") +
  xlab("Temperature treatment (ºC above ambient)") +
  guides(fill = guide_legend(ncol = 2))

sims_month
ggsave(sims_month, filename = "../03_Figures/Figure 4 - Simulations.jpg", dpi = 300, width = 3, height = 4)

to_plot_dist <- df_out %>%
  filter(
    interval == "monthly",
    time == "all"
  ) %>%
  group_by(Chamber, rep) %>%
  summarize(
    mean_hourly = sum(flux * n / sum(n)),
    tot_hourly = mean_hourly / 1000 / 1000 * (n_days * 24)
  ) %>% # Convert hourly fluxes to annual)
  left_join(annual_df %>%
    rename(tot_real = annual_flux)) %>%
  group_by(Chamber) %>%
  mutate(
    pct = (tot_hourly / tot_real * 100 - 100),
    Temp_C = sub(" ºC", "", str_extract(as.character(Chamber), "[0-9]+\\.*[0-9]* ºC")),
    Temp_C = as.numeric(sub("mb", "0", Temp_C))
  )

sims_dist <- to_plot_dist %>%
  ggplot(aes(x = as.numeric(Temp_C), y = pct, fill = Chamber)) +
  geom_hline(yintercept = 0, color = "grey85") +
  geom_smooth(method = "lm", color = "black") +
  geom_violin(aes(color = Chamber),
    draw_quantiles = c(0.5),
    position = "identity", alpha = 0.1, width = 0.5
  ) +
  scale_fill_manual(
    values = color.gradient,
    name = "Chamber"
  ) +
  scale_color_manual(
    values = color.gradient,
    name = "Chamber"
  ) +
  theme_hm +
  scale_x_continuous(
    limits = c(-0.5, 6.5),
    expand = c(0, 0)
  ) +
  theme(legend.title.position = "top") +
  ylab("Manual sampling bias (%)") +
  xlab("Temperature treatment (ºC above ambient)") +
  guides(fill = guide_legend(ncol = 2))

with_dist <- patchwork::wrap_plots(
  a = sims_month +
    guides(fill = guide_legend(ncol = 5)) +
    ylab("Manual sampling bias\n(median %)") +
    xlab("Temperature treatment (ºC above ambient)"),
  b = sims_dist + theme(legend.position = "none"),
  guides = "collect",
  axes = "collect_x"
) +
  patchwork::plot_annotation(
    tag_levels = "a",
    theme = theme(legend.position = "bottom")
  ) &
  theme(plot.tag = element_text(face = "bold"))

with_dist

ggsave(with_dist,
  filename = "../03_Figures/Figure 4 - Simulations with dist.jpg",
  dpi = 300, width = 6, height = 4
)

with_dist2 <- patchwork::wrap_plots(
  a = sims_month +
    guides(fill = guide_legend(ncol = 1)) +
    ylab("Monthly sampling bias\n(median %)") +
    xlab("Temperature treatment (ºC above ambient)"),
  b = sims_dist + theme(legend.position = "none") +
    ylab("Monthly sampling bias (%)"),
  c = sims_full_day +
    ylab("Sampling bias\n(median %)") +
    theme(
      legend.position = "none",
      axis.text.x = element_text(hjust = 0.5, angle = 0)
    ),
  d = patchwork::guide_area(),
  guides = "collect",
  axes = "collect_x",
  design = c("AAABBB
              AAABBB
              AAABBB
              CCCCDD
              CCCCDD")
) +
  patchwork::plot_annotation(
    tag_levels = "a"
  ) &
  theme(plot.tag = element_text(face = "bold"))

with_dist2

ggsave(with_dist2,
  filename = "../03_Figures/Figure 4 - Simulations all.jpg",
  dpi = 300, width = 6, height = 5
)
```

What drives residuals?

```{r}
# Load driver data
rtk <- read_csv(here::here("01_Data", "Chamber_elevation.csv")) %>%
  select(-Latitude_DD, -Longitude_DD) %>%
  mutate(Type = "") %>%
  pivot_longer(-c(Chamber, Type))
agb <- read_csv(here::here("01_Data", "Aboveground_biomass.csv"),
  show_col_types = F
) %>%
  mutate(Type = "Aboveground~biomass~(g/m^2)") %>%
  pivot_longer(-c(Chamber, Type))
stems <- read_csv(here::here("01_Data", "SCAM_Stem_measurements.csv")) %>%
  mutate(Type = "italic('S. americanus')~stem~traits") %>%
  pivot_longer(-c(Chamber, Type)) %>%
  group_by(Chamber, Type, name) %>%
  summarize(value = median(value))
counts <- read_csv(here::here("01_Data", "SCAM_Stem_counts.csv")) %>%
  mutate(Type = "italic('S. americanus')~stem~traits") %>%
  pivot_longer(-c(Chamber, Type))

drivers <- rtk %>%
  bind_rows(agb) %>%
  bind_rows(stems) %>%
  bind_rows(counts) %>%
  mutate(name = case_match(
    name,
    "Elev_m" ~ "Elevation~(m)",
    "SCAM_g_m2" ~ "C[3]",
    "TotalC4_g_m2" ~ "C[4]",
    "TotalAboveground_g_m2" ~ "Total",
    "SCAM_Height_cm" ~ "Height~(cm)",
    "SCAM_Width_mm" ~ "Width~(mm)",
    "SCAM_Stem_count" ~ "Count"
  ))

# Calculate residuals
resids <- annual_df %>%
  mutate(
    Temp_C = sub(" ºC", "", str_extract(as.character(Chamber), "[0-9]+\\.*[0-9]* ºC")),
    Temp_C = as.numeric(sub("mb", "0", Temp_C)),
    hm_pct_998 = hot_sum_998 / sum * 100,
    hm_pct_99 = hot_sum_99 / sum * 100,
    hm_pct_95 = hot_sum_95 / sum * 100
  ) %>%
  select(Chamber, Temp_C, hm_pct_998, hm_pct_99, hm_pct_95, sum) %>%
  pivot_longer(-c(Chamber, Temp_C), names_to = "HM_variable") %>%
  mutate(resid = lm(value ~ Temp_C)$residuals) %>%
  mutate(HM_variable = replace_values(
    HM_variable,
    "resid_99" ~ "Top 1%",
    "resid_998" ~ "Top 0.2%",
    "resid_95" ~ "Top 5%"
  )) %>%
  select(-value)

resids %>%
  left_join(drivers) %>%
  ggplot(aes(x = value, y = resid)) +
  geom_point(aes(color = Chamber)) +
  theme_hm +
  scale_color_manual(values = color.gradient, name = "Chamber") +
  xlab("value") +
  ylab("Residual") +
  geom_smooth(method = "lm") +
  ggpubr::stat_cor(
    aes(
      label =
        paste0(
          ..rr.label.., "~`,`~`p=`~",
          p.adjust(readr::parse_number(..p.label..),
            n = length(unique(drivers$name)) *
              length(unique(resids$HM_variable))
          )
        )
    ),
    method = "pearson", label.y = 1
  ) +
  ggh4x::facet_nested("Methane~flux~metric" + HM_variable ~ Type + name,
    scales = "free", switch = "x",
    labeller = label_parsed,
    nest_line = element_line(linewidth = 0.2)
  ) +
  theme(
    strip.placement = "outside",
    axis.title.x = element_blank()
  )
```


```{r}
resids <- annual_df %>%
  mutate(
    Temp_C = sub(" ºC", "", str_extract(as.character(Chamber), "[0-9]+\\.*[0-9]* ºC")),
    Temp_C = as.numeric(sub("mb", "0", Temp_C)),
    hm_pct_998 = hot_sum_998 / sum * 100,
    hm_pct_99 = hot_sum_99 / sum * 100,
    hm_pct_95 = hot_sum_95 / sum * 100
  ) %>%
  mutate(
    resid_99 = lm(hm_pct_99 ~ Temp_C)$residuals,
    resid_95 = lm(hm_pct_95 ~ Temp_C)$residuals,
    resid_998 = lm(hm_pct_998 ~ Temp_C)$residuals,
    resid_sum = lm(sum ~ Temp_C)$residuals
  ) %>%
  select(Chamber, resid_99, resid_95, resid_998, resid_sum)

rtk <- read_csv(here::here("Raw_Data", "GENX_RTK_11mar2026.csv")) %>%
  group_by(Chamber_ID) %>%
  summarize(Elev_m = mean(Elev_m, na.rm = T), .groups = "drop") %>%
  mutate(Chamber = factor(Chamber_ID,
    levels = 1:12,
    labels = chamber_labels2
  ))

resids %>%
  left_join(rtk) %>%
  ggplot(aes(x = Elev_m, y = resid_sum)) +
  geom_point(aes(color = Chamber)) +
  theme_hm +
  scale_color_manual(values = color.gradient, name = "Chamber") +
  xlab("Elevation (m)") +
  ylab("Residual") +
  geom_smooth(method = "lm") +
  ggpubr::stat_cor()

## BIOMASS
agb <- read_csv("../Raw_data/biomass/2025 aboveground biomass.csv", show_col_types = F) %>%
  filter(!grepl("Ref", Chamber)) %>%
  mutate(Chamber = factor(Chamber,
    levels = 1:12,
    labels = chamber_labels2
  )) %>%
  pivot_longer(cols = c(
    "SCAM.g.m2", "TotalC4.g.m2", "SPPA.g.m2", "DISP.g.m2",
    "Other.g.m2", "Above.g.m2"
  ))

resids %>%
  left_join(agb) %>%
  ggplot(aes(x = value, y = resid_99, color = Chamber)) +
  geom_point() +
  theme_hm +
  scale_color_manual(values = color.gradient, name = "Chamber") +
  xlab("Biomass (g/m2)") +
  ylab("Residual (negative means that hot moments\nare less influential than expected)") +
  facet_wrap(~name, scales = "free")

bio_label <- make_lm_label(
  data = resids %>%
    left_join(agb),
  xvar = "value",
  yvar = "resid_99",
  group_var = "name"
)

resids %>%
  pivot_longer(c(resid_99, resid_998, resid_95, resid_sum), names_to = "resid", values_to = "resid_val") %>%
  mutate(resid = replace_values(
    resid,
    "resid_sum" ~ "Total",
    "resid_99" ~ "Top 1%",
    "resid_998" ~ "Top 0.2%",
    "resid_95" ~ "Top 5%"
  )) %>%
  left_join(agb, relationship = "many-to-many") %>%
  filter(!name == "Other.g.m2") %>%
  group_by(name, resid) %>%
  mutate(p = summary(lm(resid_val ~ value))$coefficients[2, 4]) %>%
  ggplot(aes(x = value, y = resid_val)) +
  geom_smooth(method = "lm", data = . %>% filter(p < 0.05), color = "black") +
  geom_point(aes(color = Chamber)) +
  theme_hm +
  scale_color_manual(values = color.gradient, name = "Chamber") +
  xlab("Biomass (g/m2)") +
  ylab("Residual (negative means that hot moments\nare less influential than expected)") +
  facet_grid(resid ~ name, scales = "free") +
  ggpubr::stat_cor(size = 2)


# Stem width/height
library(readxl)
files <- list.files("../Raw_data/biomass", full.names = T)
stem_files <- files[grepl("1-", files)]
stems <- stem_files %>%
  map(read_excel, col_types = "text") %>%
  bind_rows() %>%
  mutate(
    chamber_ref = as.numeric(str_extract(Chamber, "[0-9]+")),
    chamber_ref = factor(chamber_ref,
      levels = 1:12,
      labels = 1:12
    ),
    `Measurement type` = ifelse(grepl("Ref", Chamber), "Reference", "Chamber"),
    Total_Height = as.numeric(Total_Height),
    Width = as.numeric(Width)
  ) %>%
  filter(
    Year == 2025,
    `Measurement type` == "Chamber"
  ) %>%
  mutate(Chamber = factor(Chamber,
    levels = 1:12,
    labels = chamber_labels2
  )) %>%
  select(Chamber, Total_Height, Width)

# Stem count
count_files <- files[grepl("2-", files)]
counts <- count_files %>%
  map(read_excel, col_types = "text") %>%
  bind_rows() %>%
  mutate(
    chamber_ref = as.numeric(str_extract(Chamber, "[0-9]+")),
    chamber_ref = factor(chamber_ref,
      levels = 1:12,
      labels = 1:12
    ),
    `Measurement type` = ifelse(grepl("Ref", Chamber), "Reference", "Chamber"),
    Count = as.numeric(ifelse(is.na(Count), StemCount, Count))
  ) %>%
  select(-StemCount)

stems_long <- stems %>%
  pivot_longer(c(Total_Height, Width))

resids %>%
  left_join(stems_long) %>%
  ggplot(aes(x = value, y = resid_99)) +
  geom_point(aes(color = Chamber)) +
  geom_smooth(method = "lm") +
  theme_hm +
  scale_color_manual(values = color.gradient, name = "Chamber") +
  facet_wrap(~name, scales = "free")

resids %>%
  pivot_longer(c(resid_99, resid_998, resid_95), names_to = "resid", values_to = "resid_val") %>%
  mutate(resid = replace_values(
    resid,
    "resid_99" ~ "Top 1%",
    "resid_998" ~ "Top 0.2%",
    "resid_95" ~ "Top 5%"
  )) %>%
  left_join(
    stems_long %>%
      group_by(Chamber, name) %>%
      summarize(value = median(value)),
    relationship = "many-to-many"
  ) %>%
  ggplot(aes(x = value, y = resid_val)) +
  geom_point(aes(color = Chamber)) +
  geom_smooth(method = "lm") +
  theme_hm +
  scale_color_manual(values = color.gradient, name = "Chamber") +
  facet_grid(resid ~ name, scales = "free")

resids %>%
  left_join(stems_long %>%
    group_by(Chamber, name) %>%
    summarize(value = mean(value))) %>%
  pivot_wider() %>%
  ggplot(aes(x = Total_Height, y = Width)) +
  geom_point()

counts <- counts %>%
  filter(
    Year == 2025,
    `Measurement type` == "Chamber"
  ) %>%
  mutate(Chamber = factor(Chamber,
    levels = 1:12,
    labels = chamber_labels2
  )) %>%
  select(Chamber, Count)

resids %>%
  left_join(counts) %>%
  ggplot(aes(x = Count, y = resid_99)) +
  geom_point(aes(color = Chamber)) +
  geom_smooth(method = "lm") +
  theme_hm +
  scale_color_manual(values = color.gradient, name = "Chamber")

resids %>%
  left_join(stems_long %>%
    group_by(Chamber, name) %>%
    summarize(value = median(value))) %>%
  bind_rows(resids %>%
    left_join(counts %>%
      pivot_longer(Count))) %>%
  left_join(rtk) %>%
  ggplot(aes(x = Elev_m, y = value)) +
  geom_point(aes(color = Chamber)) +
  geom_smooth(method = "lm") +
  facet_wrap(~name, scales = "free_y")

sa <- stems %>%
  left_join(counts) %>%
  mutate(SA = 3 * Width * Total_Height * Count)

resids %>%
  pivot_longer(c(resid_99, resid_998, resid_95), names_to = "resid", values_to = "resid_val") %>%
  mutate(resid = replace_values(
    resid,
    "resid_99" ~ "Top 1%",
    "resid_998" ~ "Top 0.2%",
    "resid_95" ~ "Top 5%"
  )) %>%
  left_join(stems_long %>%
    group_by(Chamber, name) %>%
    summarize(value = median(value)) %>%
    bind_rows(counts %>%
      pivot_longer(Count))) %>%
  pivot_wider() %>%
  mutate(SA = 3 * Width * Total_Height * Count) %>%
  left_join(agb %>%
    pivot_wider()) %>%
  select(Chamber, resid, resid_val, SA, SCAM.g.m2) %>%
  pivot_longer(c(SA, SCAM.g.m2)) %>%
  ggplot(aes(x = value, y = resid_val)) +
  geom_point(aes(color = Chamber)) +
  geom_smooth(method = "lm") +
  facet_grid(resid ~ name, scales = "free") +
  ggpubr::stat_cor()

resids %>%
  pivot_longer(c(resid_99, resid_998, resid_95, resid_sum), names_to = "resid", values_to = "resid_val") %>%
  mutate(resid = replace_values(
    resid,
    "resid_99" ~ "Top 1%",
    "resid_998" ~ "Top 0.2%",
    "resid_95" ~ "Top 5%"
  )) %>%
  left_join(sa %>%
    group_by(Chamber) %>%
    summarize(SA = median(SA))) %>%
  left_join(agb %>%
    pivot_wider()) %>%
  select(Chamber, resid, resid_val, SA, SCAM.g.m2) %>%
  pivot_longer(c(SA, SCAM.g.m2)) %>%
  ggplot(aes(x = value, y = resid_val)) +
  geom_point(aes(color = Chamber)) +
  geom_smooth(method = "lm") +
  facet_grid(resid ~ name, scales = "free") +
  ggpubr::stat_cor()
```

```{r}
hot_moments <- hm_df %>%
  mutate(season = case_when(
    month(DateTime_EST) %in% c(3:5) ~ "Spring",
    month(DateTime_EST) %in% c(6:8) ~ "Summer",
    month(DateTime_EST) %in% c(9:11) ~ "Autumn"
  )) %>%
  group_by(Chamber, season) %>%
  mutate(
    hot_moment_quant_998 = ifelse(CH4_umol_m2_h >=
      quantile(CH4_umol_m2_h,
        probs = 0.998, na.rm = TRUE
      ),
    "hot", "not"
    ),
    hot_moment_quant_99 = ifelse(CH4_umol_m2_h >=
      quantile(CH4_umol_m2_h,
        probs = 0.99, na.rm = TRUE
      ),
    "hot", "not"
    ),
    hot_moment_quant_95 = ifelse(CH4_umol_m2_h >=
      quantile(CH4_umol_m2_h,
        probs = 0.95, na.rm = TRUE
      ),
    "hot", "not"
    )
  ) %>%
  summarize(
    n = sum(!is.na(CH4_umol_m2_h)),
    sum = sum(CH4_umol_m2_h, na.rm = T) /
      n / 1000 / 1000 * (n_days * 24), # Convert hourly fluxes to growing season
    hot_sum_998 = sum(CH4_umol_m2_h[hot_moment_quant_998 == "hot"], na.rm = T) /
      n / 1000 / 1000 * (n_days * 24),
    hot_sum_99 = sum(CH4_umol_m2_h[hot_moment_quant_99 == "hot"], na.rm = T) /
      n / 1000 / 1000 * (n_days * 24),
    hot_sum_95 = sum(CH4_umol_m2_h[hot_moment_quant_95 == "hot"], na.rm = T) /
      n / 1000 / 1000 * (n_days * 24),
    min = min(DateTime_EST),
    max = max(DateTime_EST)
  )

top_pct <- hot_moments %>%
  mutate(
    Temp_C = sub(" ºC", "", str_extract(as.character(Chamber), "[0-9]+\\.*[0-9]* ºC")),
    Temp_C = as.numeric(sub("mb", "0", Temp_C)),
    hm_pct_998 = hot_sum_998 / sum * 100,
    hm_pct_99 = hot_sum_99 / sum * 100,
    hm_pct_95 = hot_sum_95 / sum * 100
  ) %>%
  select(season, Temp_C, Chamber, hm_pct_998, hm_pct_99, hm_pct_95) %>%
  pivot_longer(c(hm_pct_95, hm_pct_99, hm_pct_998)) %>%
  mutate(
    name = factor(
      name,
      levels = c("hm_pct_95", "hm_pct_99", "hm_pct_998"),
      labels = c(
        "Top 5% of measurements",
        "Top 1% of measurements",
        "Top 0.2% of measurements"
      )
    )
  ) %>%
  group_by(name, season) %>%
  mutate(
    model  = list(lm(value ~ Temp_C)),
    p      = summary(model[[1]])$coefficients[2, 4],
    r2     = summary(model[[1]])$r.squared,
    median = median(value)
  ) %>%
  ungroup()

top_pct_fig <- top_pct %>%
  ggplot(aes(x = Temp_C, y = value)) +
  geom_smooth(
    method = "lm", color = "black",
    data = ~ subset(.x, p < 0.05)
  ) +
  geom_smooth(
    method = "lm", color = "grey70",
    data = ~ subset(.x, p >= 0.05),
    lty = "51", alpha = 0.15
  ) +
  geom_point(aes(fill = Chamber),
    color = "black", shape = 21,
    stroke = 0.5, size = 2
  ) +
  geom_text(
    data = label_df,
    aes(x = -Inf, y = Inf, label = label),
    hjust = 0, vjust = 1.1,
    inherit.aes = FALSE, size = 3
  ) +
  scale_fill_manual(values = color.gradient, name = "Chamber") +
  theme_hm +
  ylab(expression(atop("Percent of growing season", "emissions"))) +
  xlab("Temperature treatment (ºC above ambient)") +
  guides(fill = guide_legend(ncol = 4)) +
  facet_grid(name ~ season, scales = "free_y")

top_pct_fig
```

