---
title: "Drivers and CH4"
author: "Abby Lewis"
date: "2024-08-22"
output: html_document
---

Methods from Ari's paper and this one https://agupubs.onlinelibrary.wiley.com/doi/full/10.1002/2015JG003054

Load data and packages

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)

library(tidyverse)
library(data.table)
library(waveslim)
library(DescTools)
source("wavelet_functions.R")
source("make_lm_label.R")
source("hm_style.R")

ch4 <- read_csv(here::here("01_Data", "GENX_flux_data_interpolated_with_drivers.csv"))
soil_temp <- read_csv(here::here("01_Data", "Soil_temp.csv")) %>%
  rename(time_join = DateTime_EST)

ch4 <- ch4 %>%
  mutate(time_join = round_date(DateTime_EST, "15 minutes")) %>%
  left_join(soil_temp) %>%
  mutate(Chamber = factor(Chamber, levels = chamber_labels))
```

Run wavelet

```{r}
drivers <- c(
  "AirTemp_C",
  "SoilTemp_C",
  "Depth_cm",
  "GPP_umol_m2_h",
  "Salinity",
  "Reco_umol_m2_h"
)

driver_labels <- c(
  AirTemp_C = "Air temperature",
  SoilTemp_C = "Soil temperature",
  Depth_cm = "Water depth",
  GPP_umol_m2_h = "GPP",
  GPP_unfilled = "GPP",
  Salinity = "Salinity",
  Reco_umol_m2_h = "Reco_umol_m2_h"
)

driver_colors <- c(
  AirTemp_C = "#E76D66",
  SoilTemp_C = "brown4",
  Depth_cm = "#2176AB",
  GPP_umol_m2_h = "#3BAA5D",
  GPP_unfilled = "#3BAA5D",
  Salinity = "#6A4C93",
  Reco_umol_m2_h = "#264653"
)

# Apply across all treatments and sites
grid <- ch4 %>%
  pivot_longer(
    cols = c("CH4_umol_m2_h", drivers),
    # NOTE: I've also tried EVI and PAR but they don't add much
    names_to = "var_name", values_to = "value"
  )

dfs <- map(unique(grid$var_name),
  double_map,
  ch4 = ch4,
  treatment = unique(ch4$Chamber),
  timestep_s = 7800
) %>%
  bind_rows()

# Re-introduce NAs
nas_to_add <- ch4 %>%
  mutate(
    na_ch4 = ifelse(is.na(CH4_umol_m2_h_not_gapfilled), T, F),
    na_gpp = ifelse(is.na(GPP_umol_m2_h_not_gapfilled), T, F)
  ) %>%
  select(DateTime_EST, Chamber, na_ch4, na_gpp) %>%
  distinct()

# Group wavelet scales into interpretable bins
discrete_scales <- dfs %>%
  mutate(
    name = as.character(name),
    num_value = as.numeric(gsub("[^0-9]", "", name)),
    grouped_scale = case_when(
      grepl("days", name) & num_value < 30 ~ "Weekly",
      grepl("hours", name) & num_value < 10 ~ "Hourly",
      grepl("hours", name) & num_value >= 10 ~ "Daily",
      TRUE ~ "Seasonal"
    )
  ) %>%
  select(-num_value) %>%
  group_by(grouped_scale, Chamber, DateTime_EST, var_name) %>%
  summarize(
    value = sum(value, na.rm = T),
    reconstructed = sum(reconstructed, na.rm = T),
    .groups = "drop"
  ) %>%
  pivot_wider(names_from = var_name, values_from = c(value, reconstructed)) %>%
  rename_with(~ gsub("value_", "", .x)) %>%
  left_join(nas_to_add) %>%
  mutate(
    CH4_unfilled = ifelse(na_ch4, NA, CH4_umol_m2_h),
    GPP_unfilled = ifelse(na_gpp, NA, GPP_umol_m2_h),
    Chamber = factor(Chamber,
      levels = chamber_labels
    ),
    grouped_scale = factor(grouped_scale,
      levels = c("Hourly", "Daily", "Weekly", "Seasonal")
    )
  ) %>%
  select(-na_ch4, -na_gpp)

# Separate explanatory variables
discrete_scales_exp <- discrete_scales %>%
  dplyr::select(-matches("CH4_unfilled|CH4_umol_m2_h|GPP_unfilled|recon")) %>%
  pivot_longer(
    cols = -c(grouped_scale, Chamber, DateTime_EST),
    names_to = "exp_var", values_to = "exp_var_value"
  ) %>%
  filter(!is.na(exp_var_value)) %>%
  rename(grouped_scale_exp = grouped_scale)
```

Plot overall variance

```{r}
grouped_pct_var <- dfs %>%
  mutate(
    name = as.character(name),
    num_value = as.numeric(gsub("[^0-9]", "", name)),
    grouped_scale = case_when(
      grepl("days", name) & num_value < 30 ~ "Weekly",
      grepl("hours", name) & num_value < 10 ~ "Hourly",
      grepl("hours", name) & num_value >= 10 ~ "Daily",
      TRUE ~ "Seasonal"
    )
  ) %>%
  select(-num_value) %>%
  group_by(grouped_scale, Chamber, DateTime_EST, var_name) %>%
  summarize(
    value = sum(value),
    .groups = "drop"
  ) %>%
  filter(var_name == "CH4_umol_m2_h") %>%
  group_by(grouped_scale, Chamber, var_name) %>%
  summarize(var = var(value, na.rm = T)) %>%
  group_by(Chamber, var_name) %>%
  mutate(tot_var = sum(var, na.rm = T)) %>%
  ungroup() %>%
  mutate(
    Chamber = factor(Chamber,
      levels = chamber_labels
    ),
    grouped_scale = factor(grouped_scale,
      levels = c("Hourly", "Daily", "Weekly", "Seasonal")
    ),
    Temp_C = sub(" ºC", "", str_extract(as.character(Chamber), "[0-9]+\\.*[0-9]* ºC")),
    Temp_C = as.numeric(sub("mb", "0", Temp_C))
  )

scale_labels <- make_lm_label(
  data = grouped_pct_var %>% mutate(sd = sqrt(var)),
  xvar = "Temp_C",
  yvar = "sd",
  group_var = "grouped_scale"
)

scales <- grouped_pct_var %>%
  mutate(sd = sqrt(var)) %>%
  ggplot(aes(x = Temp_C, y = sd)) +
  geom_smooth(method = "lm", color = "black") +
  geom_point(aes(fill = Chamber), size = 2, stroke = 0.5, shape = 21) +
  geom_text(
    aes(x = -Inf, y = Inf, label = label),
    hjust = 0, vjust = 1.1,
    inherit.aes = FALSE,
    size = 3,
    data = scale_labels
  ) +
  scale_fill_manual(values = color.gradient, name = "Chamber") +
  facet_wrap(~grouped_scale) +
  theme_hm +
  ylab(expression("Standard deviation (µmol" ~ m^-2 ~ h^-1 * ")")) +
  xlab("Temperature treatment (ºC above ambient)")

h_to_s_data <- grouped_pct_var %>%
  group_by(Chamber, Temp_C) %>%
  summarise(
    h_to_s = sqrt(var[grouped_scale == "Hourly"]) /
      sqrt(var[grouped_scale == "Seasonal"]),
    .groups = "drop"
  )

h_to_s_label <- make_lm_label(
  data = h_to_s_data,
  xvar = "Temp_C",
  yvar = "h_to_s"
)

h_to_s <- h_to_s_data %>%
  ggplot(aes(x = Temp_C, y = h_to_s)) +
  geom_smooth(method = "lm", color = "black") +
  geom_point(aes(fill = Chamber), size = 2, stroke = 0.5, shape = 21) +
  geom_text(
    aes(x = -Inf, y = Inf, label = label),
    hjust = 0, vjust = 1.1,
    inherit.aes = FALSE,
    size = 3,
    data = h_to_s_label
  ) +
  scale_fill_manual(values = color.gradient, name = "Chamber") +
  theme_hm +
  ylab("Hourly : seasonal") +
  xlab("Temperature treatment\n(ºC above ambient)")

ggsave(
  h_to_s +
    guides(fill = guide_legend(ncol = 2)),
  filename = "../03_Figures/h_to_s.png", width = 4, height = 4
)

barchart <- grouped_pct_var %>%
  mutate(
    sd = sqrt(var),
    grouped_scale = factor(grouped_scale,
      levels = rev(levels(grouped_scale))
    )
  ) %>%
  ggplot(aes(x = Chamber, y = var / tot_var, fill = grouped_scale)) +
  geom_col(color = "black", linewidth = 0.2, width = 0.8) +
  theme_hm +
  scale_fill_manual(
    values = c("grey95", "grey80", "grey40", "grey15"),
    name = "Scale"
  ) +
  ylab(expression("Proportion of total variance")) +
  theme(
    axis.text.x = element_text(angle = 45, hjust = 1),
    axis.title.x = element_blank()
  )

scales_bar <- patchwork::wrap_plots(
  scales +
    theme(axis.title.x = element_text(vjust = 15)),
  barchart +
    guides(fill = guide_legend(ncol = 1)) +
    theme(
      legend.justification = "right",
      plot.background = element_rect(fill = NULL),
      axis.text.x = element_text(
        size = 8,
        margin = ggplot2::margin(b = 0, unit = "pt")
      )
    ),
  guides = "collect", widths = c(1.3, 1)
) +
  patchwork::plot_annotation(tag_levels = "a") &
  theme(
    plot.tag = element_text(face = "bold", size = 14),
    plot.tag.position = c(0.02, 0.98),
    legend.position = "bottom",
    legend.margin = ggplot2::margin(t = -10, unit = "pt"),
    legend.box.margin = ggplot2::margin(t = 0, unit = "cm"),
    legend.box.spacing = unit(0, "cm"),
    plot.margin = ggplot2::margin(b = 0, t = 0, r = 5, l = 5, unit = "pt")
  )

ggsave(scales_bar, filename = "../03_Figures/wavelet_scales_bar.png", width = 7, height = 4.5)
```

Figure showing altered variability (maybe for SI?)

```{r}
example <- discrete_scales %>%
  filter(grouped_scale == "Seasonal" |
    month(DateTime_EST) == 7 & day(DateTime_EST) %in% 8:14 & grouped_scale == "Weekly" |
    month(DateTime_EST) == 7 & day(DateTime_EST) %in% 8:14 & grouped_scale == "Daily" |
    month(DateTime_EST) == 7 & day(DateTime_EST) %in% 8:14 & grouped_scale == "Hourly") %>%
  mutate(grouped_scale = factor(grouped_scale, levels = rev(levels(grouped_scale)))) %>%
  ggplot(aes(x = DateTime_EST, y = reconstructed_CH4_umol_m2_h, color = Chamber)) +
  geom_line() +
  ylab(expression("Methane flux (µmol" ~ m^-2 ~ h^-1 * ")")) +
  facet_wrap(~grouped_scale, scales = "free_x") +
  scale_color_manual(values = color.gradient, name = "Chamber") +
  theme_hm +
  scale_x_datetime(
    labels = function(x) {
      ifelse(
        format(x, "%d") == "01",
        format(x, "%b"),
        format(x, "%b %d")
      )
    }
  ) +
  theme(axis.title.x = element_blank())

example

ggsave(example, filename = "../03_Figures/wavelet_example.png", width = 5, height = 3.5)

discrete_scales %>%
  mutate(
    grouped_scale = factor(grouped_scale, levels = rev(levels(grouped_scale))),
    Chamber = factor(Chamber,
      levels = levels(Chamber),
      labels = sub(" \\(.+\\)", "", levels(Chamber))
    )
  ) %>%
  ggplot(aes(x = DateTime_EST, y = reconstructed_CH4_umol_m2_h, color = Chamber)) +
  geom_line() +
  ylab(expression("Methane flux (µmol" ~ m^-2 ~ h^-1 * ")")) +
  facet_grid(grouped_scale ~ Chamber, scales = "free") +
  scale_color_manual(values = color.gradient, name = "Chamber") +
  theme_hm +
  scale_x_datetime(
    breaks = seq(
      from = as.POSIXct("2020-04-01"),
      to   = max(discrete_scales$DateTime_EST, na.rm = TRUE),
      by   = "6 months"
    ),
    date_labels = "%b"
  ) +
  theme(
    axis.title.x = element_blank(),
    legend.position = "none"
  )

ggsave(filename = "../03_Figures/Figure 5 - wavelet_comprehensive.png", width = 10, height = 3.5)
```

Spearman

```{r}
# Calculate Spearman correlation
spearman_corrs <- discrete_scales %>%
  dplyr::select(c(grouped_scale, Chamber, DateTime_EST, CH4_umol_m2_h)) %>%
  left_join(discrete_scales_exp, relationship = "many-to-many") %>%
  filter(
    !is.na(exp_var_value),
    !is.na(CH4_umol_m2_h)
  ) %>%
  group_by(Chamber, grouped_scale, exp_var, grouped_scale_exp) %>%
  summarize(
    spearman_rho = cor(exp_var_value, CH4_umol_m2_h,
      method = "spearman",
      use = "complete.obs"
    ),
    spearman_rho2 = spearman_rho^2,
    .groups = "drop"
  )

relative_corr <- spearman_corrs %>%
  filter(
    grouped_scale == grouped_scale_exp,
    !exp_var == "evi_predicted"
  ) %>%
  mutate(
    abs_rho = abs(spearman_rho)
  )

# Maybe for SI
ggplot(
  relative_corr,
  aes(
    x = grouped_scale,
    y = abs_rho,
    color = exp_var,
    group = exp_var
  )
) +
  geom_point(size = 0.5) +
  geom_line() +
  facet_wrap(~Chamber) +
  xlab("Wavelet scale of variation") +
  ylab("Absolute Spearman correlation (|ρ|)") +
  scale_color_manual(
    values = driver_colors[drivers],
    labels = driver_labels[drivers],
    name = "Explanatory variable"
  ) +
  theme_hm +
  theme(axis.text.x = element_text(angle = 45, hjust = 1))

relative_corr %>%
  ggplot(aes(
    x = grouped_scale,
    y = abs_rho,
    color = exp_var,
    group = exp_var
  )) +
  geom_line(alpha = 0.1, aes(group = paste0(Chamber, exp_var))) +
  geom_line(
    data = . %>% group_by(exp_var, grouped_scale) %>%
      summarize(abs_rho = mean(abs_rho)),
    linewidth = 1.5
  ) +
  xlab("Wavelet scale of variation") +
  ylab("Spearman correlation |ρ|)") +
  scale_color_manual(
    values = driver_colors[drivers],
    labels = driver_labels[drivers],
    name = "Explanatory variable"
  ) +
  theme_hm +
  theme(axis.text.x = element_text(angle = 45, hjust = 1))

spear <- relative_corr %>%
  ggplot(aes(
    x = grouped_scale,
    y = spearman_rho,
    color = exp_var,
    group = exp_var
  )) +
  geom_hline(color = "grey50", yintercept = 0) +
  geom_line(alpha = 0.1, aes(group = paste0(Chamber, exp_var))) +
  geom_line(
    data = . %>% group_by(exp_var, grouped_scale) %>%
      summarize(spearman_rho = mean(spearman_rho)),
    linewidth = 1.5
  ) +
  scale_x_discrete(expand = c(0, 0.4)) +
  xlab("Wavelet scale of variation") +
  ylab("Spearman correlation (ρ)") +
  scale_color_manual(
    values = driver_colors[drivers],
    labels = driver_labels[drivers],
    name = "Explanatory variable"
  ) +
  guides(color = guide_legend(ncol = 2)) +
  theme_hm +
  theme(axis.text.x = element_text(angle = 45, hjust = 1))

spear

ggsave(spear, filename = "../03_Figures/Figure 6 - Spearman correlations.png", width = 3, height = 4)

relative_corr %>%
  mutate(
    Temp_C = sub(" ºC", "", str_extract(as.character(Chamber), "[0-9]+\\.*[0-9]* ºC")),
    Temp_C = as.numeric(sub("mb", "0", Temp_C))
  ) %>%
  ggplot(aes(
    x = Temp_C, y = spearman_rho,
    color = Chamber
  )) +
  geom_point() +
  facet_grid(exp_var ~ grouped_scale)
```


```{r}
# library(mgcv)

discrete_scales %>%
  mutate(
    tod = hour(DateTime_EST) +
      minute(DateTime_EST) / 60 +
      second(DateTime_EST) / 3600
  ) %>%
  filter(grouped_scale == "Daily") %>%
  ggplot(aes(x = tod, y = reconstructed_CH4_umol_m2_h, color = Chamber)) +
  geom_smooth(
    method = "gam",
    formula = y ~ s(x, bs = "cc", k = 12),
    se = FALSE
  ) +
  scale_x_continuous(limits = c(0, 24), breaks = seq(0, 24, 6)) +
  scale_color_manual(values = color.gradient) +
  theme_hm

ch4 %>%
  mutate(
    Chamber = factor(Chamber,
      levels = chamber_labels
    ),
    tod = hour(DateTime_EST) +
      minute(DateTime_EST) / 60 +
      second(DateTime_EST) / 3600
  ) %>%
  ggplot(aes(x = tod, y = CH4_umol_m2_h, color = Chamber)) +
  geom_smooth(
    method = "gam",
    formula = y ~ s(x, bs = "cc", k = 12),
    se = FALSE
  ) +
  scale_x_continuous(limits = c(0, 24), breaks = seq(0, 24, 6)) +
  scale_color_manual(values = color.gradient) +
  theme_hm

ch4 %>%
  mutate(
    Chamber = factor(Chamber,
      levels = chamber_labels
    ),
    tod = hour(DateTime_EST) +
      minute(DateTime_EST) / 60 +
      second(DateTime_EST) / 3600,
    season = case_when(
      month(DateTime_EST) %in% c(3:5) ~ "Spring",
      month(DateTime_EST) %in% c(6:8) ~ "Summer",
      month(DateTime_EST) %in% c(9:11) ~ "Autumn"
    )
  ) %>%
  ggplot(aes(x = tod, y = CH4_umol_m2_h, color = Chamber)) +
  geom_smooth(
    method = "gam",
    formula = y ~ s(x, bs = "cc", k = 12),
    se = FALSE
  ) +
  scale_x_continuous(limits = c(0, 24), breaks = seq(0, 24, 6)) +
  scale_color_manual(values = color.gradient) +
  theme_hm +
  facet_wrap(~season)

ch4 %>%
  mutate(
    Chamber = factor(Chamber,
      levels = chamber_labels
    ),
    tod = hour(DateTime_EST) +
      minute(DateTime_EST) / 60 +
      second(DateTime_EST) / 3600
  ) %>%
  ggplot(aes(x = tod, y = GPP_umol_m2_h, color = Chamber)) +
  geom_smooth(
    method = "gam",
    formula = y ~ s(x, bs = "cc", k = 12),
    se = FALSE
  ) +
  scale_x_continuous(limits = c(0, 24), breaks = seq(0, 24, 6)) +
  scale_color_manual(values = color.gradient) +
  theme_hm

discrete_scales %>%
  mutate(
    tod = hour(DateTime_EST) +
      minute(DateTime_EST) / 60 +
      second(DateTime_EST) / 3600
  ) %>%
  filter(grouped_scale == "Daily") %>%
  ggplot(aes(x = tod, y = reconstructed_GPP_umol_m2_h, color = Chamber)) +
  geom_smooth(
    method = "gam",
    formula = y ~ s(x, bs = "cc", k = 12),
    se = FALSE
  ) +
  scale_x_continuous(limits = c(0, 24), breaks = seq(0, 24, 6)) +
  scale_color_manual(values = color.gradient) +
  theme_hm

ch4 %>%
  mutate(
    tod = hour(DateTime_EST) +
      minute(DateTime_EST) / 60 +
      second(DateTime_EST) / 3600
  ) %>%
  ggplot(aes(x = tod, y = CO2_umol_m2_h, color = Chamber)) +
  geom_smooth(
    method = "gam",
    formula = y ~ s(x, bs = "cc", k = 12),
    se = FALSE
  ) +
  scale_x_continuous(limits = c(0, 24), breaks = seq(0, 24, 6)) +
  scale_color_manual(values = color.gradient) +
  theme_hm
```

Resids

```{r}
# Load driver data
rtk <- read_csv(here::here("01_Data", "Chamber_elevation.csv")) %>%
  select(-Latitude_DD, -Longitude_DD) %>%
  mutate(Type = "") %>%
  pivot_longer(-c(Chamber, Type))
agb <- read_csv(here::here("01_Data", "Aboveground_biomass.csv"),
  show_col_types = F
) %>%
  mutate(Type = "Aboveground~biomass~(g/m^2)") %>%
  pivot_longer(-c(Chamber, Type))
stems <- read_csv(here::here("01_Data", "SCAM_Stem_measurements.csv")) %>%
  mutate(Type = "italic('S. americanus')~stem~traits") %>%
  pivot_longer(-c(Chamber, Type)) %>%
  group_by(Chamber, Type, name) %>%
  summarize(value = median(value))
counts <- read_csv(here::here("01_Data", "SCAM_Stem_counts.csv")) %>%
  mutate(Type = "italic('S. americanus')~stem~traits") %>%
  pivot_longer(-c(Chamber, Type))

drivers <- rtk %>%
  bind_rows(agb) %>%
  bind_rows(stems) %>%
  bind_rows(counts) %>%
  mutate(name = case_match(
    name,
    "Elev_m" ~ "Elevation~(m)",
    "SCAM_g_m2" ~ "C[3]",
    "TotalC4_g_m2" ~ "C[4]",
    "TotalAboveground_g_m2" ~ "Total",
    "SCAM_Height_cm" ~ "Height~(cm)",
    "SCAM_Width_mm" ~ "Width~(mm)",
    "SCAM_Stem_count" ~ "Count"
  ))

# Calculate residuals
resids <- grouped_pct_var %>%
  group_by(grouped_scale) %>%
  mutate(resid = lm(var ~ Temp_C)$residuals) %>%
  select(grouped_scale, resid, Chamber)

resids %>%
  left_join(drivers) %>%
  ggplot(aes(x = value, y = resid)) +
  geom_point(aes(color = Chamber)) +
  theme_hm +
  scale_color_manual(values = color.gradient, name = "Chamber") +
  xlab("value") +
  ylab("Residual") +
  geom_smooth(method = "lm") +
  ggpubr::stat_cor(
    aes(
      label =
        paste0(
          ..rr.label.., "~`,`~`p=`~",
          p.adjust(readr::parse_number(..p.label..),
            n = length(unique(drivers$name)) *
              length(unique(resids$grouped_scale))
          )
        )
    ),
    method = "pearson", label.y = 180
  ) +
  ggh4x::facet_nested("Wavelet~scale" + grouped_scale ~ Type + name,
    scales = "free_x", switch = "x",
    labeller = label_parsed,
    nest_line = element_line(linewidth = 0.2)
  ) +
  theme(
    strip.placement = "outside",
    axis.title.x = element_blank()
  )
```
