---
title: "Other stats"
author: "Abby Lewis"
date: "2024-08-22"
output: html_document
---

## Overview

This file contains code to calculate relevant statistics for manuscript text.

### Table of contents:

-   Step 1: Load data and packages
-   Step 2: Calculate inundation and salinity


## Step 1: Load data and packages

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)

# Load packages
library(tidyverse)
library(patchwork)
library(mgcv)
source("R/hm_style.R")

# Load data
ch4 <- read_csv(here::here("01_Data", "GENX_flux_data_interpolated_with_drivers.csv")) %>%
  mutate(DateTime_EST = with_tz(DateTime_EST, tz = "EST"),
         Chamber = factor(Chamber, levels = chamber_labels),
         date = as_date(DateTime_EST)
  )

n_days <- as.numeric(difftime(max(ch4$DateTime_EST),
  min(ch4$DateTime_EST),
  units = "days"
))
```

Calculate percent

```{r}
# Only use days that have data from all 12 chambers
hm_df <- ch4 %>%
  filter(!is.na(CH4_umol_m2_h)) %>%
  group_by(date) %>%
  filter(length(unique(Chamber)) == 12)

# Calculate the contribution of ebullitive fluxes
hot_moments <- hm_df %>%
  group_by(Chamber) %>%
  # Calculate sum of fluxes that exceed each threshold
  # and convert to growing season total (mol/m2/y from umol/m2/h)
  summarize(
    n = sum(!is.na(CH4_umol_m2_h)),
    annual_flux = sum(CH4_umol_m2_h, na.rm = T) /
      n / 1000 / 1000 * (n_days * 24),
    hot_sum_eb = sum(CH4_umol_m2_h[!is.na(Ebullition_yn) & Ebullition_yn]) /
      n / 1000 / 1000 * (n_days * 24)
  ) %>%
  mutate( # Add temperature treatment
    Temp_C = sub(" ºC", "", str_extract(as.character(Chamber), "-*[0-9]+\\.*[0-9]* ºC")),
    Temp_C = as.numeric(sub("mb", "0", Temp_C))
  )

# Calculate summary stats about the contribution of extreme events
top_pct <- hot_moments %>%
  mutate(
    hm_pct_eb = hot_sum_eb / annual_flux * 100,
  ) %>%
  select(Temp_C, Chamber, hm_pct_eb)
```

Ebullition figure

```{r}
names(color.gradient) <- chamber_labels
chamber_scale <- scale_fill_manual(
  limits = chamber_labels,
  values = color.gradient,
  name = "Chamber",
  drop = FALSE
)

eb_number <- ch4 %>%
  filter(!is.na(CH4_umol_m2_h)) %>%
  group_by(date) %>%
  filter(length(unique(Chamber)) == 12) %>%
  group_by(Chamber) %>%
  summarize(
    n = sum(Ebullition_yn, na.rm = TRUE),
    pct = n / sum(!is.na(Ebullition_yn)) * 100
  ) %>%
  mutate(
    Temp_C = sub(
      " ºC", "",
      str_extract(
        as.character(Chamber),
        "-*[0-9]+\\.*[0-9]* ºC"
      )
    ),
    Temp_C = as.numeric(sub("mb", "0", Temp_C))
  ) %>%
  ggplot(aes(x = Temp_C, y = pct)) +
  geom_smooth(method = "gam",
              formula = y ~ s(x, k = 3),
              method.args = list(method = "REML",
                                 family = mgcv::tw(link = "log")),
              color = "black") +
  geom_point(
    aes(fill = Chamber),
    color = "black",
    shape = 21,
    stroke = 0.5,
    size = 2
  ) +
  chamber_scale +
  theme_hm +
  ylab(expression(atop("Ebullitive fluxes", "(% of all fluxes)"))) +
  xlab("Temperature treatment (ºC above ambient)") +
  guides(fill = guide_legend(ncol = 4))


eb_magnitude <- ch4 %>%
  filter(!is.na(CH4_umol_m2_h)) %>%
  group_by(date) %>%
  filter(length(unique(Chamber)) == 12) %>%
  group_by(Chamber) %>%
  filter(
    !is.na(Ebullition_yn),
    Ebullition_yn
  ) %>%
  mutate(
    Temp_C = sub(
      " ºC", "",
      str_extract(
        as.character(Chamber),
        "-*[0-9]+\\.*[0-9]* ºC"
      )
    ),
    Temp_C = as.numeric(sub("mb", "0", Temp_C))
  ) %>%
  ggplot(aes(x = Temp_C, y = CH4_umol_m2_h)) +
  geom_point(
    aes(color = Chamber),
    shape = 21,
    stroke = 0.5,
    size = 2
  ) +
  scale_color_manual(
    limits = chamber_labels,
    values = color.gradient,
    name = "Chamber",
    drop = FALSE
  ) +
  theme_hm +
  ylab(expression(atop(
    "Ebullition magnitude",
    "(µmol" ~ m^-2 ~ h^-1 * ")"
  ))) +
  xlab("Temperature treatment (ºC above ambient)") +
  guides(fill = guide_legend(ncol = 4))

eb_annual <- top_pct %>%
  ggplot(aes(x = Temp_C, y = hm_pct_eb)) +
  geom_smooth(method = "gam",
              formula = y ~ s(x, k = 3),
              method.args = list(method = "REML",
                                 family = mgcv::tw(link = "log")),
              color = "black") +
  geom_point(
    aes(fill = Chamber),
    color = "black",
    shape = 21,
    stroke = 0.5,
    size = 2
  ) +
  chamber_scale +
  theme_hm +
  ylab(expression(atop(
    "Ebullitive emissions",
    "(% of growing season emissions)"
  ))) +
  xlab("Temperature treatment (ºC above ambient)") +
  guides(fill = guide_legend(ncol = 4))

comb <- patchwork::wrap_plots(
  a = eb_number,
  b = eb_magnitude + theme(legend.position = "none"),
  c = eb_annual + theme(legend.position = "none"),
  nrow = 1,
  ncol = 3,
  axis_titles = "collect"
) +
  plot_annotation(tag_levels = "a") &
  theme(
    plot.tag = element_text(face = "bold"))
    
comb

ggsave(
  comb,
  filename = "../03_Figures/SI/SI - Ebullition.jpg",
  dpi = 300, width = 6, height = 3.5
)
```

When does ebullition happen

```{r}
when <- ch4 %>%
  ggplot(aes(x = Depth_cm, y = CH4_umol_m2_h, color = Ebullition_yn))+
  geom_vline(aes(xintercept = 0)) +
  geom_point(alpha = 0.2, color = "grey50")+
  geom_point(data = . %>% filter(!is.na(Ebullition_yn) & Ebullition_yn),
             color = "red") +
  facet_wrap(~Chamber, scales = "free_y")+
  theme_hm

ggsave(
  when,
  filename = "../03_Figures/SI/SI - Depth_eb.jpg",
  dpi = 300, width = 6, height = 4
)
```
