---
title: "Other stats"
author: "Abby Lewis"
date: "2024-08-22"
output: html_document
---

## Overview

This file contains code to calculate relevant statistics for manuscript text.

### Table of contents:

-   Step 1: Load data and packages
-   Step 2: Calculate inundation and salinity


## Step 1: Load data and packages

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)

# Load packages
library(tidyverse)

# Load data
ch4 <- read_csv(here::here("01_Data", "GENX_flux_data_interpolated_with_drivers.csv"))
```


## Step 2: Calculate inundation and salinity

```{r}
ch4 %>%
  summarize(n_flooded = sum(Depth_cm > 0, na.rm = T) / sum(!is.na(Depth_cm)))

ch4 %>%
  summarize(median_sal = median(Salinity, na.rm = T), 
            min_sal = min(Salinity, na.rm = T), 
            max_sal = max(Salinity, na.rm = T))
```

## Step 3: Calculate ebullition

```{r}
ch4 %>%
  group_by(Chamber) %>%
  summarize(n_eb = sum(Ebullition_yn, na.rm = T),
            pct_eb = n_eb / sum(!is.na(Ebullition_yn)),
            n_tot = sum(!is.na(Ebullition_yn)))
```

```{r}
ch4 %>%
  filter(!is.na(CH4_umol_m2_h), 
         CH4_umol_m2_h > 0) %>%
  group_by(Chamber) %>%
  summarize(gini = DescTools::Gini(CH4_umol_m2_h),
            kurtosis = e1071::kurtosis(CH4_umol_m2_h, na.rm = TRUE, type = 2),
            skewness = e1071::skewness(CH4_umol_m2_h, na.rm = TRUE, type = 2)) %>%
  pivot_longer(c(gini, skewness, kurtosis)) %>%
  mutate( # Add temperature treatment
    Temp_C = sub(" ºC", "", str_extract(as.character(Chamber), "-*[0-9]+\\.*[0-9]* ºC")),
    Temp_C = as.numeric(sub("mb", "0", Temp_C)),
    Chamber = factor(Chamber, levels = chamber_labels),
    name = factor(name,
                  levels = c("skewness", "kurtosis", "gini"),
                  labels = c("Skewness", "Kurtosis", "Gini Coefficient"))
  ) %>%
  ggplot(aes(x = Temp_C, y = value))+
  geom_point(aes(fill = Chamber),
    color = "black", shape = 21,
    stroke = 0.5, size = 2
  ) +
  geom_smooth(method = "gam",
              formula = y ~ s(x, k = 3),
              method.args = list(method = "REML"),
              color = "black",
              data = . %>%
                filter(name == "Gini Coefficient")) +
  geom_smooth(method = "gam",
              formula = y ~ s(x, k = 3),
              method.args = list(method = "REML",
                                 family = mgcv::tw(link = "log")),
              color = "black",
              data = . %>%
                filter(name != "Gini Coefficient")) +
  theme_hm +
  facet_wrap(~name, scales = "free_y")+
  scale_fill_manual(values = color.gradient, name = "Chamber") +
  xlab("Temperature treatment (ºC above ambient)")
```

