---
title: "Biomass"
author: "Abby Lewis"
date: "2026-02-23"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)

# Load packages and data

# Packages
library(tidyverse)
library(readxl)

# Biomass
files <- list.files("../Raw_data/biomass", full.names = T)
agb <- files[grepl("aboveground", files)]
df <- agb %>%
  map(read_csv, show_col_types = F) %>%
  bind_rows() %>%
  mutate(
    chamber_ref = as.numeric(str_extract(Chamber, "[0-9]+")),
    chamber_ref = factor(chamber_ref,
      levels = 1:12,
      labels = 1:12
    ),
    `Measurement type` = ifelse(grepl("Ref", Chamber), "Reference", "Chamber")
  )

# Stem width/height
stem_files <- files[grepl("1-", files)]
stems <- stem_files %>%
  map(read_excel, col_types = "text") %>%
  bind_rows() %>%
  mutate(
    chamber_ref = as.numeric(str_extract(Chamber, "[0-9]+")),
    chamber_ref = factor(chamber_ref,
      levels = 1:12,
      labels = 1:12
    ),
    `Measurement type` = ifelse(grepl("Ref", Chamber), "Reference", "Chamber"),
    Total_Height = as.numeric(Total_Height),
    Width = as.numeric(Width)
  )

# Stem count
count_files <- files[grepl("2-", files)]
counts <- count_files %>%
  map(read_excel, col_types = "text") %>%
  bind_rows() %>%
  mutate(
    chamber_ref = as.numeric(str_extract(Chamber, "[0-9]+")),
    chamber_ref = factor(chamber_ref,
      levels = 1:12,
      labels = 1:12
    ),
    `Measurement type` = ifelse(grepl("Ref", Chamber), "Reference", "Chamber"),
    Count = as.numeric(ifelse(is.na(Count), StemCount, Count))
  ) %>%
  select(-StemCount)
```

Plot biomass

```{r}
df %>%
  ggplot(aes(x = chamber_ref, y = Above.g.m2)) +
  geom_col(position = "dodge") +
  facet_grid(`Measurement type` ~ Year)

df %>%
  ggplot(aes(x = chamber_ref, y = SCAM.g.m2)) +
  geom_col(position = "dodge") +
  facet_grid(`Measurement type` ~ Year)

df %>%
  ggplot(aes(x = chamber_ref, y = DISP.g.m2)) +
  geom_col(position = "dodge") +
  facet_grid(`Measurement type` ~ Year)

df %>%
  ggplot(aes(x = chamber_ref, y = SPPA.g.m2)) +
  geom_col(position = "dodge") +
  facet_grid(`Measurement type` ~ Year)

df %>%
  ggplot(aes(x = chamber_ref, y = SPPA.g.m2 + DISP.g.m2)) +
  geom_col(position = "dodge") +
  facet_grid(`Measurement type` ~ Year)

df %>%
  pivot_longer(c(SPPA.g.m2, DISP.g.m2, SCAM.g.m2)) %>%
  ggplot(aes(x = chamber_ref, y = value, fill = name)) +
  geom_col() +
  facet_grid(`Measurement type` ~ Year)

df %>%
  pivot_longer(c(SPPA.g.m2, DISP.g.m2, SCAM.g.m2)) %>%
  mutate(name = ifelse(name %in% c("SPPA.g.m2", "DISP.g.m2"),
    "grass", "sedge"
  )) %>%
  ggplot(aes(x = chamber_ref, y = value, fill = name)) +
  geom_col() +
  facet_grid(`Measurement type` ~ Year)
```

Map

```{r}
lat_lon <- read_csv(here::here("Raw_data", "GENX_RTK_11mar2026.csv")) %>%
  filter(!is.na(Elev_m),
         !is.na(Chamber_ID)) %>%
  mutate(
    lat_dd = as.numeric(sub("N", "", Lat)),
    lon_dd = -as.numeric(sub("W", "", Lon))
  ) %>%
  group_by(Chamber_ID) %>%
  summarize(across(c(lat_dd, lon_dd, Elev_m), mean)) %>%
  rename(chamber_ref = Chamber_ID)

library(sf)

df_map_sf <- df %>%
  mutate(chamber_ref = as.numeric(chamber_ref)) %>%
  left_join(lat_lon) %>%
  st_as_sf(coords = c("lon_dd", "lat_dd"), crs = 4326)

veg_map <- df_map_sf %>%
  pivot_longer(c(SPPA.g.m2, DISP.g.m2, SCAM.g.m2)) %>%
  mutate(name = ifelse(name %in% c("SPPA.g.m2", "DISP.g.m2"),
                       "grass", "sedge")) %>%
  group_by(`Measurement type`, Year, chamber_ref, name) %>%
  summarize(value = sum(value))

ggplot(veg_map) +
  geom_sf(aes(color = value), size = 3) +
  facet_grid(`Measurement type`+name ~ Year) +
  scale_color_viridis_c(name = "Biomass (g)")+
  egg::theme_article()+
  theme(axis.text.x = element_text(angle = 90, hjust = 1))

veg_map %>%
  filter(`Measurement type` == "Chamber") %>%
  ggplot() +
  geom_sf(aes(color = value), size = 3) +
  facet_grid(name ~ Year) +
  scale_color_viridis_c(name = "Biomass (g)")+
  egg::theme_article()+
  theme(axis.text.x = element_text(angle = 90, hjust = 1))+
  ggtitle("In chambers")

veg_map %>%
  filter(`Measurement type` == "Reference") %>%
  ggplot() +
  geom_sf(aes(color = value), size = 3) +
  facet_grid(name ~ Year) +
  scale_color_viridis_c(name = "Biomass (g)")+
  egg::theme_article()+
  theme(axis.text.x = element_text(angle = 90, hjust = 1))+
  ggtitle("Reference")
```

Plot stem characteristics

```{r}
stem_sum <- stems %>%
  group_by(chamber_ref, `Measurement type`, Year) %>%
  summarize(
    u_height = mean(Total_Height, na.rm = T),
    med_height = median(Total_Height, na.rm = T),
    sd_height = sd(Total_Height, na.rm = T),
    u_width = mean(Width, na.rm = T),
    med_width = median(Width, na.rm = T),
    sd_width = sd(Width, na.rm = T),
    .groups = "drop"
  )

stems %>%
  ggplot(aes(x = chamber_ref)) +
  geom_boxplot(aes(y = Total_Height)) +
  facet_grid(`Measurement type` ~ Year)

stems %>%
  ggplot(aes(x = chamber_ref)) +
  geom_boxplot(aes(y = Width)) +
  facet_grid(`Measurement type` ~ Year)
```

Plot stem counts

```{r}
counts %>%
  ggplot(aes(x = chamber_ref, y = Count)) +
  geom_col(position = "dodge") +
  facet_grid(`Measurement type` ~ Year)
```

